export const departmentMap: Record<string, number> = {
  "Administracija (MVK)": 1,
  "Administracija (OK)": 2,
  "Administracija (PSI)": 3,
  "Administracija (SL)": 4,
  "Administracija (TUB)": 5,
  "Akių ligų skyrius (SL)": 11,
  "Akušerijos skyrius (MVK)": 12,
  "Ambulatorinės chirurgijos skyrius (SL)": 13,
  "Anesteziologijos - operacijų skyrius (SL)": 14,
  "Apskaitos ir biudžeto skyrius (SL)": 15,
  "Ausų, nosies, gerklės ligų skyrius (SL)": 16,
  "Onkologijos skyrius (OK)": 17,
  "Chirurgijos reanimacijos ir intensyviosios terapijos skyrius (SL)": 18,
  "Energetikos skyrius (SL)": 19,
  "Ginekologijos skyrius (MVK)": 20,
  "I chirurgijos skyrius (SL)": 21,
  "Pulmonologijos skyrius (TUB)": 22,
  "II chirurgijos skyrius (SL)": 23,
  "Tuberkuliozės skyrius (TUB)": 24,
  "Infekcijų kontrolės skyrius (SL)": 25,
  "Informacinių technologijų skyrius (SL)": 10,
  "Infrastruktūros skyrius (SL)": 26,
  "Dokumentų valdymo ir klientų aptarnavimo skyrius (SL)": 27,
  "Kardiologijos reanimacijos ir intensyviosios terapijos skyrius (SL)": 28,
  "Klinikinės diagnostikos laboratorija (TUB)": 29,
  "Klinikinės fiziologijos skyrius (SL)": 30,
  "Konsultacijų skyrius (OK)": 31,
  "Konsultacijų skyrius (SL)": 32,
  "Konsultacijų skyrius (TUB)": 33,
  "Kraujo bankas (SL)": 34,
  "Laboratorinės diagnostikos skyriaus padalinys (MVK)": 35,
  "Laboratorinės diagnostikos skyriaus padalinys (OK)": 36,
  "Laboratorinės diagnostikos skyrius (SL)": 37,
};

export const categoryMap: Record<string, number> = {
  DVS: 1,
  "Elektroninis paštas": 2,
  ESIS: 3,
  "Kita (NE KROVIMO DARBAI)": 4,
  Kompiuteris: 5,
  medDream: 6,
  Pirkimai: 7,
  Spausdintuvas: 8,
  "Tabeliai-Grafikai": 9,
  Vartotojai: 10,
};